### ISSUE TITLE
Links are being mangled

### ISSUE THREAD

**Issue by j23n** [lostinhaste/Justified-Swipebox#1]
Hello there, 

I wanted to try out your plugin. 

I created a new post in the web interface, copied the example code and hit publish. Upon reloading the post, this is the resulting Markdown content:

```
<div id="gardenGlow2023" class="justified-gallery">
   {{< justified-swipebox-entry photo="[lostinhaste.com/uploads/2...](https://lostinhaste.com/uploads/2023/garden-glow-01-full.jpg)" >}}
   {{< justified-swipebox-entry photo="[lostinhaste.com/uploads/2...](https://lostinhaste.com/uploads/2023/garden-glow-02-full.jpg)" >}}
   {{< justified-swipebox-entry photo="[lostinhaste.com/uploads/2...](https://lostinhaste.com/uploads/2023/garden-glow-03-full.jpg)" >}}
   {{< justified-swipebox-entry photo="[lostinhaste.com/uploads/2...](https://lostinhaste.com/uploads/2023/garden-glow-04-full.jpg)" >}}
<div>

{{< justified-swipebox-gallery id="gardenGlow2023" rowHeight="200" >}}
```

Somewhere along the way, the image URLs seem to be replaced by markdown links. What am I doing wrong?

**Comment by lostinhaste** [comment]
Hey @johanneswindelen, thanks for trying out my plugin! 😄 This is a bug in Micro.blog, I've let Manton and the help team know about it but it's been a while and I haven't heard anything back. There is a work-around for this, I embed links in a _hidden_ `div` before I then put them in the `justified-swipebox-entry` shortcode entries.

```
<!-- Adding these to the page so that the shortcode doesn't break -->
<div style="display: none">
<img src="https://lostinhaste.com/uploads/2023/garden-glow-01-full.jpg" />
<img src="https://lostinhaste.com/uploads/2023/garden-glow-02-full.jpg" />
<img src="https://lostinhaste.com/uploads/2023/garden-glow-03-full.jpg" />
<img src="https://lostinhaste.com/uploads/2023/garden-glow-04-full.jpg" />
</div>

<div id="gardenGlow2023" class="justified-gallery">
   {{< justified-swipebox-entry photo="https://lostinhaste.com/uploads/2023/garden-glow-01-full.jpg" >}}
   {{< justified-swipebox-entry photo="https://lostinhaste.com/uploads/2023/garden-glow-02-full.jpg" >}}
   {{< justified-swipebox-entry photo="https://lostinhaste.com/uploads/2023/garden-glow-03-full.jpg" >}}
   {{< justified-swipebox-entry photo="https://lostinhaste.com/uploads/2023/garden-glow-04-full.jpg" >}}
<div>

{{< justified-swipebox-gallery id="gardenGlow2023" rowHeight="200" >}}
```

You can see this on my [Holiday Lights @ the Gardens 🎄📷](https://lostinhaste.com/2023/12/15/holiday-lights-the.html) post on my site, if you go look at the source-code:

![hidden-photos](https://github.com/lostinhaste/Justified-Swipebox/assets/639894/88e49287-ec6d-4bb8-b8dd-6b02424d690d)

I need to reach out to the Help team at Micro.blog and remind them this is an issue...and I _really_ need to go update my documentation for the plugin, to warn about this a little better.

Let me know if you have any questions about the plugin or any suggestions. Thanks for trying it out!
